const express = require("express");
const cors = require("cors");

const app = express();
const PORT = process.env.PORT || 5000;

app.use(cors());
app.use(express.json());
const jobs = [
  {
    id: 1,
    title: "Frontend Developer",
    company: "TechCorp Solutions",
    location: "Pune, India",
    salary: "₹6 LPA",
    type: "Full-Time",
    experience: "0-2 years",
    skills: ["React.js", "JavaScript", "CSS", "Redux"],
  },
  {
    id: 2,
    title: "React Developer",
    company: "WebSolutions Pvt Ltd",
    location: "Mumbai, India",
    salary: "₹5.5 LPA",
    type: "Full-Time",
    experience: "1-3 years",
    skills: ["React.js", "Next.js", "TypeScript"],
  },
  {
    id: 3,
    title: "UI/UX Designer",
    company: "DesignX Studio",
    location: "Bangalore, India",
    salary: "₹7 LPA",
    type: "Remote",
    experience: "2+ years",
    skills: ["Figma", "Adobe XD", "CSS"],
  },
  {
    id: 4,
    title: "Full Stack Developer",
    company: "Innovate Inc",
    location: "Delhi, India",
    salary: "₹8.5 LPA",
    type: "Full-Time",
    experience: "2-5 years",
    skills: ["React.js", "Node.js", "MongoDB"],
  },
  {
    id: 5,
    title: "Backend Developer",
    company: "CodeCrafters",
    location: "Hyderabad, India",
    salary: "₹7.2 LPA",
    type: "Hybrid",
    experience: "1-4 years",
    skills: ["Node.js", "Express.js", "SQL"],
  },
  {
    id: 6,
    title: "Software Engineer",
    company: "ByteWave Tech",
    location: "Chennai, India",
    salary: "₹6.8 LPA",
    type: "Full-Time",
    experience: "0-3 years",
    skills: ["React.js", "Django", "REST API"],
  },
  {
    id: 7,
    title: "React Native Developer",
    company: "AppMasters",
    location: "Remote",
    salary: "₹6.5 LPA",
    type: "Remote",
    experience: "1-3 years",
    skills: ["React Native", "Redux", "Firebase"],
  },
  {
    id: 8,
    title: "Junior Frontend Developer",
    company: "CodeSphere",
    location: "Noida, India",
    salary: "₹5 LPA",
    type: "Full-Time",
    experience: "0-1 years",
    skills: ["JavaScript", "React.js", "Bootstrap"],
  },
  {
    id: 9,
    title: "Senior React Developer",
    company: "CloudStack Labs",
    location: "Pune, India",
    salary: "₹12 LPA",
    type: "Full-Time",
    experience: "4+ years",
    skills: ["React.js", "GraphQL", "TypeScript"],
  },
  {
    id: 10,
    title: "Frontend Engineer",
    company: "TechFusion",
    location: "Bangalore, India",
    salary: "₹9 LPA",
    type: "Hybrid",
    experience: "3-5 years",
    skills: ["React.js", "Vue.js", "CSS"],
  },
  {
    id: 11,
    title: "Junior JavaScript Developer",
    company: "ByteLogic",
    location: "Hyderabad, India",
    salary: "₹4.8 LPA",
    type: "Full-Time",
    experience: "0-2 years",
    skills: ["JavaScript", "React.js", "HTML", "CSS"],
  },
  {
    id: 12,
    title: "Product Designer",
    company: "DesignHive",
    location: "Remote",
    salary: "₹7.5 LPA",
    type: "Remote",
    experience: "3+ years",
    skills: ["Figma", "Sketch", "Adobe Illustrator"],
  },
  {
    id: 13,
    title: "Web Developer",
    company: "TechVista",
    location: "Pune, India",
    salary: "₹6 LPA",
    type: "Full-Time",
    experience: "1-3 years",
    skills: ["React.js", "HTML5", "CSS3", "JavaScript"],
  },
  {
    id: 14,
    title: "Next.js Developer",
    company: "WebGenics",
    location: "Delhi, India",
    salary: "₹8 LPA",
    type: "Full-Time",
    experience: "2-4 years",
    skills: ["Next.js", "React.js", "TypeScript", "GraphQL"],
  },
  {
    id: 15,
    title: "MERN Stack Developer",
    company: "CodeNation",
    location: "Bangalore, India",
    salary: "₹10 LPA",
    type: "Hybrid",
    experience: "3-6 years",
    skills: ["MongoDB", "Express.js", "React.js", "Node.js"],
  },
  {
    id: 16,
    title: "Senior UI Developer",
    company: "PixelWorks",
    location: "Chennai, India",
    salary: "₹11 LPA",
    type: "Full-Time",
    experience: "4-6 years",
    skills: ["React.js", "CSS Modules", "Tailwind CSS"],
  },
  {
    id: 17,
    title: "Angular Developer",
    company: "DevOrbit",
    location: "Mumbai, India",
    salary: "₹7 LPA",
    type: "Full-Time",
    experience: "2-4 years",
    skills: ["Angular", "TypeScript", "SCSS"],
  },
  {
    id: 18,
    title: "Freelance React Developer",
    company: "Self-Employed",
    location: "Remote",
    salary: "₹5 LPA",
    type: "Freelance",
    experience: "1+ years",
    skills: ["React.js", "Redux", "Firebase"],
  },
  {
    id: 19,
    title: "Software Developer",
    company: "NeuralTech",
    location: "Delhi, India",
    salary: "₹8.2 LPA",
    type: "Full-Time",
    experience: "2-4 years",
    skills: ["JavaScript", "React.js", "GraphQL", "Apollo"],
  },
  {
    id: 20,
    title: "Lead Frontend Engineer",
    company: "HyperCode",
    location: "Bangalore, India",
    salary: "₹14 LPA",
    type: "Full-Time",
    experience: "5+ years",
    skills: ["React.js", "Vue.js", "Micro Frontends"],
  },
  {
    id: 21,
    title: "Associate Frontend Developer",
    company: "CodeSprint",
    location: "Pune, India",
    salary: "₹4.5 LPA",
    type: "Full-Time",
    experience: "0-1 years",
    skills: ["JavaScript", "HTML", "CSS", "React.js"],
  },
  {
    id: 22,
    title: "Frontend Architect",
    company: "CloudFront",
    location: "Hyderabad, India",
    salary: "₹16 LPA",
    type: "Full-Time",
    experience: "6+ years",
    skills: ["React.js", "TypeScript", "GraphQL", "Microservices"],
  },
  {
    id: 23,
    title: "Junior Web Designer",
    company: "DesignCrew",
    location: "Chennai, India",
    salary: "₹4.2 LPA",
    type: "Full-Time",
    experience: "0-2 years",
    skills: ["HTML", "CSS", "JavaScript", "Figma"],
  },
  {
    id: 24,
    title: "React.js Intern",
    company: "Startup X",
    location: "Remote",
    salary: "₹3 LPA",
    type: "Internship",
    experience: "0-1 years",
    skills: ["React.js", "JavaScript", "Bootstrap"],
  },
  {
    id: 25,
    title: "Next.js Engineer",
    company: "AIWorks",
    location: "Bangalore, India",
    salary: "₹10 LPA",
    type: "Full-Time",
    experience: "3-5 years",
    skills: ["Next.js", "React.js", "Tailwind CSS", "Firebase"],
  },
];

app.get("/api/jobs", (req, res) => {
  res.json(jobs);
});

app.listen(PORT, () => console.log(`Server running on port ${PORT}`));
